passing all tests

diff --git a/bin/search b/bin/search
--- a/bin/search
+++ b/bin/search
@@ -1,81 +1,74 @@
 #!/bin/bash
-LOG_DIR="var/log"
-LOG_FILE="$LOG_DIR/search.log"
-SEARCH_DB="var/search.sqlite3"
-SEARCH_PORT=8000
-SEARCH_PROCESS="flask --app search run --host 0.0.0.0 --port $SEARCH_PORT"
-
 set -Eeuo pipefail
 
-# Check if arguments are provided
-if [ $# -eq 0 ]; then
-    echo "Usage: $0 {start|stop|restart|status}"
+LOG_DIR="var/log"
+LOG_FILE="$LOG_DIR/search.log"
+FLASK_CMD="flask --app search run --host 0.0.0.0 --port 8000"
+
+start_server() {
+  echo "starting search server ..."
+
+  mkdir -p "$LOG_DIR"
+
+  if [ ! -f "var/search.sqlite3" ]; then
+    echo "Error: can't find search database var/search.sqlite3"
+    echo "Try: ./bin/searchdb"
     exit 1
-fi
+  fi
 
-function start_search() {
-    if [ ! -f "$SEARCH_DB" ]; then
-        echo "Error: can't find search database $SEARCH_DB"
-        exit 1
-    fi
+  ./bin/index status
+  if [ $? -ne 0 ]; then
+    echo "Error: index server is not running"
+    exit 1
+  fi
 
-    ./bin/index status > /dev/null
-    if [ $? -ne 0 ]; then
-        echo "Error: index server is not running"
-        echo "Try ./bin/index start"
-        exit 1
-    fi
+  if pgrep -f "$FLASK_CMD" > /dev/null; then
+    echo "Search server is already running"
+    exit 1
+  fi
 
-    pgrep -f "$SEARCH_PROCESS" > /dev/null
-    if [ $? -eq 0 ]; then
-        echo "Error: search server is already running"
-        exit 1
-    fi
-
-    # Start the Search server
-    echo "starting search server ..."
-    mkdir -p "$LOG_DIR"
-    rm -f "$LOG_FILE"
-    flask --app search run --host 0.0.0.0 --port $SEARCH_PORT &> "$LOG_FILE" &
-
+  rm -f "$LOG_FILE"
+  echo "+ $FLASK_CMD &> $LOG_FILE &"
+  $FLASK_CMD &> "$LOG_FILE" &
 }
 
-function stop_search() {
-    echo "stopping search server ..."
-    pkill -f "$SEARCH_PROCESS" || true
+stop_server() {
+  echo "stopping search server ..."
+  pkill -f "$FLASK_CMD" || true
 }
 
-function restart_search() {
-    stop_search
-    start_search
-}
-
-function status_search() {
-    pgrep -f "$SEARCH_PROCESS" > /dev/null
-    if [ $? -eq 0 ]; then
-        echo "search server running"
-        exit 0
-    else
-        echo "search server stopped"
-        exit 1
-    fi
+status_server() {
+  set +o pipefail
+  NPROCS=$(pgrep -f "$FLASK_CMD" | wc -l)
+  set -o pipefail
+  if [ "$NPROCS" -eq 1 ]; then
+    echo "search server running"
+    exit 0
+  elif [ "$NPROCS" -eq 0 ]; then
+    echo "search server stopped"
+    exit 1
+  else
+    echo "search server error: found ${NPROCS} processes, expected 1"
+    exit 2
+  fi
 }
 
 case "$1" in
-    start)
-        start_search
-        ;;
-    stop)
-        stop_search
-        ;;
-    restart)
-        restart_search
-        ;;
-    status)
-        status_search
-        ;;
-    *)
-        echo "Usage: $0 {start|stop|restart|status}"
-        exit 1
-        ;;
+  start)
+    start_server
+    ;;
+  stop)
+    stop_server
+    ;;
+  status)
+    status_server
+    ;;
+  restart)
+    stop_server
+    start_server
+    ;;
+  *)
+    echo "Usage: $0 {start|stop|status|restart}"
+    exit 1
+    ;;
 esac
